version: '2'

services:

  docker-av:
    container_name: docker-av

    build:
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - ./data/queue:/data/av/queue
      - ./data/ok:/data/av/ok
      - ./data/nok:/data/av/nok
    
    networks:
      - avnetwork

networks:
  avnetwork:
